export default {
  getListModule: [
    {
      title: "ASSISTANT QA MODULE",
      icon: "inventory",
      link: "#/AssistantQATable",
    },
    {
      title: "QA MODULE",
      icon: "assignment",
      link: "#/QATable",
    },
    {
      title: "DIRECTORS MODULE",
      icon: "article",
      link: "#/DirectorTable",
    },
    {
      title: "HR MODULE",
      icon: "chrome_reader_mode",
      link: "#/HRTable",
    },
    {
      title: "AUDIT MODULE",
      icon: "assessment",
      link: "#/AuditTable",
    },
  ],
  getListDefaultModule: [
    {
      title: "DASHBOARD",
      icon: "dashboard",
      link: "#/Dashboard",
    },
    {
      title: "REPORT MODULE",
      icon: "summarize",
      link: "#/ReportTable",
    },
  ],
  getAccessModule: [],
  getGoogleUser: [],
  getDash: [],
  getDirector: [],
  getAssistantQA: [],
  getAssistantQAForm: [],
  getAssistantSubCode: [],
  getAssistantDivision: [],
  getCountSubs: [],
  getIRForm: [],
  getQAForm: [],
  getQACon: [],
  getQA: [],
  getActionItem: [],
  getRemarks: [],
  getForm: [],
  getAudit: [],
  getSubject: [],
  getRisk: [],
  getUser: [],
  user: null,
  departments: [],
  subjectcategory: [],
  subjectname: [],
  division: [],
  employees: [],
  demerit: [],
};
