export default {
  getGoogleUser: [],
  getDash: [],
  getDirector: [],
  getCountSubs: [],
  getIRForm: [],
  getQAForm: [],
  getQACon: [],
  getQA: [],
  getActionItem: [],
  getRemarks: [],
  getForm: [],
  getAudit: [],
  getSubject: [],
  getUser: [],
  user: null,
  departments: [],
  employees: [],
  demerit: [],
};
